server {
  listen 80;
  client_max_body_size 300m;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  location /api/ { proxy_pass http://backend:8000; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; }
  location /media/ { proxy_pass http://backend:8000; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; }
  location / { proxy_pass http://frontend:5173; proxy_set_header Host $host; }
}
