export type Media = {
  id: string;
  kind: "image" | "video" | "document";
  caption: string;
  position: number;
  is_primary: boolean;
  url: string;
  status: string;
};
export type Property = {
  public_id: string;
  id?: string;
  title: string;
  slug: string;
  public_description: string;
  property_type: string;
  purpose: string;
  status: string;
  price: string | null;
  condominium_fee?: string | null;
  iptu?: string | null;
  price_on_request: boolean;
  city: string;
  neighborhood: string;
  public_reference: string;
  approximate_latitude?: string | null;
  approximate_longitude?: string | null;
  bedrooms: number | null;
  suites: number | null;
  bathrooms: number | null;
  parking_spaces: number | null;
  private_area: string | null;
  total_area?: string | null;
  land_dimensions: string;
  features: string[];
  accepts_financing?: boolean | null;
  accepts_exchange?: boolean | null;
  featured: boolean;
  launch?: boolean;
  is_launch?: boolean;
  exclusive?: boolean;
  review_color: string;
  review_label?: string;
  media: Media[];
  published?: boolean;
  hidden?: boolean;
  private_address?: string;
  private_commission?: string;
  internal_notes?: string;
  reviewed_at?: string | null;
  created_at?: string;
};
export type Page<T> = {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
};
export type ListingOption = {
  id: string;
  kind: "property_type" | "city" | "neighborhood";
  name: string;
  city: string;
  active: boolean;
};
export type Lead = {
  id: string;
  name: string;
  phone: string;
  email: string;
  message: string;
  origin: string;
  property: string | null;
  property_title: string;
  status: string;
  preferred_visit_date?: string | null;
  preferred_visit_period?: string;
  created_at: string;
};
export type CRMPropertyLink = {
  id: string;
  contact: string;
  contact_name?: string;
  property: string | null;
  property_title?: string;
  relationship: "owner" | "co_owner" | "interested" | "representative";
  development_name: string;
  unit_reference: string;
  ownership_share?: string | null;
  active: boolean;
};
export type CRMContact = {
  id: string;
  name: string;
  person_type: "individual" | "company";
  document?: string | null;
  phone: string;
  email: string;
  address: string;
  city: string;
  state: string;
  postal_code: string;
  profile: "general" | "owner" | "buyer" | "seller" | "investor" | "partner";
  source: string;
  source_detail: string;
  tags: string[];
  notes: string;
  assigned_broker?: string | null;
  broker_name?: string;
  marketing_consent: boolean;
  do_not_contact: boolean;
  status: "active" | "archived";
  opportunity_count: number;
  pending_task_count: number;
  property_links: CRMPropertyLink[];
  created_at: string;
};
export type CRMOpportunity = {
  id: string;
  contact: string;
  contact_name: string;
  property?: string | null;
  property_title?: string;
  title: string;
  stage: "new" | "contacted" | "visit" | "proposal" | "negotiation" | "won" | "lost" | "paused";
  broker?: string | null;
  broker_name?: string;
  expected_value?: string | null;
  source: string;
  next_action_at?: string | null;
  loss_reason: string;
  notes: string;
  proposal_count: number;
  updated_at: string;
};
export type CRMTask = {
  id: string;
  contact: string;
  contact_name: string;
  opportunity?: string | null;
  property?: string | null;
  property_title?: string;
  kind: string;
  title: string;
  description: string;
  due_at: string;
  status: "pending" | "completed" | "canceled";
};
export type CRMProposal = {
  id: string;
  opportunity: string;
  contact_name: string;
  property_title?: string;
  version: number;
  status: "draft" | "sent" | "analysis" | "counter" | "accepted" | "rejected" | "expired";
  total_value: string;
  down_payment: string;
  financing_value: string;
  installments: Array<{ count?: number; value?: string; note?: string }>;
  annual_reinforcements: Array<{ count?: number; value?: string; note?: string }>;
  exchanges: Array<{ description: string; value?: string }>;
  valid_until?: string | null;
  notes: string;
  created_at: string;
};
export type CRMActivity = {
  id: string;
  contact: string;
  opportunity?: string | null;
  kind: string;
  description: string;
  actor_name?: string;
  created_at: string;
};
export type CRMImportBatch = {
  id: string;
  source_label: string;
  status: "processing" | "review" | "committed" | "failed";
  total_rows: number;
  valid_rows: number;
  duplicate_rows: number;
  error_rows: number;
  imported_rows: number;
  errors: string[];
  created_at: string;
};
export type CRMImportRow = {
  id: string;
  batch: string;
  row_number: number;
  normalized_data: Record<string, string>;
  status: "valid" | "duplicate" | "error" | "imported" | "ignored";
  errors: string[];
  matched_contact?: string | null;
  matched_contact_name?: string;
  matched_property?: string | null;
  matched_property_title?: string;
};
export type AdminSession = {
  username: string;
  role: "admin" | "manager" | "broker";
  broker_id?: string | null;
  broker_name: string;
  can_view_all_crm: boolean;
  can_manage_site: boolean;
  can_manage_team: boolean;
};
export type CRMNotification = {
  id: string;
  kind: "assignment" | "task_due" | "task_overdue" | "opportunity" | "system";
  priority: "low" | "normal" | "high";
  title: string;
  message: string;
  link: string;
  read_at?: string | null;
  created_at: string;
};
export type CRMBroker = {
  id: string;
  name: string;
  phone: string;
  email: string;
  whatsapp: string;
  role: "manager" | "broker";
  active: boolean;
  user_username?: string;
};
export type CRMReport = {
  period: { date_from: string; date_to: string };
  metrics: {
    new_contacts: number; new_opportunities: number; won: number; lost: number;
    conversion_rate: number; pipeline_value: number; won_value: number;
    average_cycle_days: number; overdue_tasks: number; completed_visits: number; sent_proposals: number;
  };
  by_stage: Array<{ stage: string; label: string; total: number; value: number }>;
  by_source: Array<{ source: string; total: number }>;
  loss_reasons: Array<{ loss_reason: string; total: number }>;
  broker_performance: Array<{ broker_id: string; broker_name: string; opportunities: number; won: number; lost: number; conversion_rate: number; won_value: number; overdue_tasks: number }>;
  trend: Array<{ date: string; opportunities: number; won: number }>;
};
export type FilterOptions = {
  property_types: string[];
  cities: string[];
  neighborhoods: string[];
  bedrooms: number[];
  suites: number[];
  bathrooms: number[];
  parking_spaces: number[];
  features: string[];
  min_price: number;
  max_price: number;
  max_area: number;
};
export type SiteSettings = {
  company_name?: string;
  slogan?: string;
  whatsapp?: string;
  phone?: string;
  email?: string;
  address?: string;
  instagram?: string;
  facebook?: string;
  linkedin?: string;
  youtube?: string;
  tiktok?: string;
  about_title?: string;
  about_text?: string;
  team_title?: string;
  team_text?: string;
  hero_video_src?: string;
  hero_poster_src?: string;
  hero_video_enabled?: boolean;
};
export type HeroSlide = { id: string; title: string; subtitle: string; image_src: string; link_url: string; link_label: string; active?: boolean; position?: number };
export type Testimonial = { id: string; name: string; role: string; text: string; photo_src?: string; active?: boolean; position?: number };
export type FAQ = { id: string; question: string; answer: string; active?: boolean; position?: number };
export type InstitutionalImage = { id: string; section: "company" | "team"; title: string; text: string; image_src: string; active?: boolean; position?: number };
export type PublicContent = { hero_slides: HeroSlide[]; testimonials: Testimonial[]; faqs: FAQ[]; institutional_images: InstitutionalImage[] };
