export type Media = {
  id: string;
  kind: "image" | "video" | "document";
  caption: string;
  position: number;
  is_primary: boolean;
  url: string;
  status: string;
};
export type Property = {
  public_id: string;
  id?: string;
  title: string;
  slug: string;
  public_description: string;
  property_type: string;
  purpose: string;
  status: string;
  price: string | null;
  condominium_fee?: string | null;
  iptu?: string | null;
  price_on_request: boolean;
  city: string;
  neighborhood: string;
  public_reference: string;
  approximate_latitude?: string | null;
  approximate_longitude?: string | null;
  bedrooms: number | null;
  suites: number | null;
  bathrooms: number | null;
  parking_spaces: number | null;
  private_area: string | null;
  total_area?: string | null;
  land_dimensions: string;
  features: string[];
  accepts_financing?: boolean | null;
  accepts_exchange?: boolean | null;
  featured: boolean;
  launch?: boolean;
  is_launch?: boolean;
  exclusive?: boolean;
  review_color: string;
  review_label?: string;
  media: Media[];
  published?: boolean;
  hidden?: boolean;
  private_address?: string;
  private_commission?: string;
  internal_notes?: string;
  reviewed_at?: string | null;
  created_at?: string;
};
export type Page<T> = {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
};
export type Lead = {
  id: string;
  name: string;
  phone: string;
  email: string;
  message: string;
  origin: string;
  property: string | null;
  property_title: string;
  status: string;
  preferred_visit_date?: string | null;
  preferred_visit_period?: string;
  created_at: string;
};
export type FilterOptions = {
  property_types: string[];
  cities: string[];
  neighborhoods: string[];
  bedrooms: number[];
  suites: number[];
  bathrooms: number[];
  parking_spaces: number[];
  features: string[];
  min_price: number;
  max_price: number;
  max_area: number;
};
export type SiteSettings = {
  company_name?: string;
  slogan?: string;
  whatsapp?: string;
  phone?: string;
  email?: string;
  address?: string;
  instagram?: string;
  facebook?: string;
  linkedin?: string;
  youtube?: string;
  tiktok?: string;
  about_title?: string;
  about_text?: string;
  team_title?: string;
  team_text?: string;
};
export type HeroSlide = { id: string; title: string; subtitle: string; image_src: string; link_url: string; link_label: string; active?: boolean; position?: number };
export type Testimonial = { id: string; name: string; role: string; text: string; photo_src?: string; active?: boolean; position?: number };
export type FAQ = { id: string; question: string; answer: string; active?: boolean; position?: number };
export type InstitutionalImage = { id: string; section: "company" | "team"; title: string; text: string; image_src: string; active?: boolean; position?: number };
export type PublicContent = { hero_slides: HeroSlide[]; testimonials: Testimonial[]; faqs: FAQ[]; institutional_images: InstitutionalImage[] };
