# Generated by Django 5.2.1 on 2026-06-09 02:34

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('external_link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='In Mare Negócios Imobiliários', max_length=160)),
                ('slogan', models.CharField(default='Conectando pessoas a imóveis únicos.', max_length=240)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.models.public_code, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('public_description', models.TextField(blank=True)),
                ('property_type', models.CharField(default='Casa', max_length=80)),
                ('purpose', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Aluguel'), ('season', 'Temporada')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('available', 'Disponível'), ('reserved', 'Reservado'), ('negotiating', 'Em negociação'), ('sold', 'Vendido'), ('rented', 'Alugado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_on_request', models.BooleanField(default=False)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('neighborhood', models.CharField(db_index=True, max_length=120)),
                ('public_reference', models.CharField(blank=True, max_length=240)),
                ('approximate_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approximate_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('private_address', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suites', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('private_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_dimensions', models.CharField(blank=True, max_length=60)),
                ('solar_orientation', models.CharField(blank=True, max_length=80)),
                ('features', models.JSONField(blank=True, default=list)),
                ('accepts_financing', models.BooleanField(blank=True, null=True)),
                ('accepts_exchange', models.BooleanField(blank=True, null=True)),
                ('private_commission', models.CharField(blank=True, max_length=120)),
                ('internal_notes', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.broker')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='media/%Y/%m/')),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('quarantine', 'Quarentena'), ('ready', 'Pronto'), ('rejected', 'Rejeitado')], default='quarantine', max_length=20)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.development')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('origin', models.CharField(default='contact', max_length=80)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em atendimento'), ('converted', 'Convertido'), ('discarded', 'Descartado')], default='new', max_length=20)),
                ('consent', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.broker')),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.development')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(max_length=500)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('review', 'Aguardando revisão'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('suggestions', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='core.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['published', 'hidden', 'status'], name='core_proper_publish_b7cb78_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='core_proper_city_5e4604_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('property__isnull', False), ('development__isnull', False), _connector='OR'), name='media_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('kind', 'image')), fields=('property',), name='one_primary_property_image'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('kind', 'image')), fields=('development',), name='one_primary_development_image'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('property', 'sha256'), name='unique_property_media_hash'),
        ),
    ]
