# Generated by Django 5.2.1 on 2026-06-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['position', 'created_at']},
        ),
    ]
