# Generated by Django 5.2.1 on 2026-08-03 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_hero_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('person_type', models.CharField(choices=[('individual', 'Pessoa física'), ('company', 'Pessoa jurídica')], default='individual', max_length=20)),
                ('document', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('normalized_email', models.CharField(blank=True, db_index=True, editable=False, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('profile', models.CharField(choices=[('general', 'Contato'), ('owner', 'Proprietário'), ('buyer', 'Comprador'), ('seller', 'Vendedor'), ('investor', 'Investidor'), ('partner', 'Parceiro')], db_index=True, default='general', max_length=20)),
                ('source', models.CharField(db_index=True, default='manual', max_length=80)),
                ('source_detail', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('archived', 'Arquivado')], db_index=True, default='active', max_length=20)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to='core.broker')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='quarantine/crm-imports/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('review', 'Aguardando revisão'), ('committed', 'Importado'), ('failed', 'Falhou')], db_index=True, default='processing', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('valid', 'Pronto'), ('duplicate', 'Possível duplicidade'), ('error', 'Com erro'), ('imported', 'Importado'), ('ignored', 'Ignorado')], db_index=True, max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.crmimportbatch')),
                ('matched_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='core.crmcontact')),
                ('matched_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_import_rows', to='core.property')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='CRMOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('new', 'Lead recebido'), ('contacted', 'Contato realizado'), ('visit', 'Visita agendada'), ('proposal', 'Proposta enviada'), ('negotiation', 'Negociação'), ('won', 'Fechado'), ('lost', 'Perdido'), ('paused', 'Pausado')], db_index=True, default='new', max_length=20)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(db_index=True, default='manual', max_length=80)),
                ('next_action_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='core.broker')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='core.crmcontact')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='core.property')),
                ('source_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunity', to='core.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('note', 'Observação'), ('call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visit', 'Visita'), ('stage_change', 'Mudança de etapa'), ('proposal', 'Proposta'), ('import', 'Importação')], db_index=True, default='note', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.crmcontact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.crmopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMPropertyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('owner', 'Proprietário'), ('co_owner', 'Coproprietário'), ('interested', 'Interessado'), ('representative', 'Representante')], default='owner', max_length=20)),
                ('development_name', models.CharField(blank=True, max_length=200)),
                ('unit_reference', models.CharField(blank=True, max_length=120)),
                ('ownership_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='core.crmcontact')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='core.property')),
            ],
            options={
                'ordering': ['development_name', 'unit_reference', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('analysis', 'Em análise'), ('counter', 'Contraproposta'), ('accepted', 'Aceita'), ('rejected', 'Recusada'), ('expired', 'Expirada')], db_index=True, default='draft', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('financing_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('installments', models.JSONField(blank=True, default=list)),
                ('annual_reinforcements', models.JSONField(blank=True, default=list)),
                ('exchanges', models.JSONField(blank=True, default=list)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.crmopportunity')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('follow_up', 'Follow-up'), ('call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visit', 'Visita'), ('other', 'Outro')], default='follow_up', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to='core.broker')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.crmcontact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.crmopportunity')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to='core.property')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['status', 'profile'], name='core_crmcon_status_11b866_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_crm_import_row'),
        ),
        migrations.AddIndex(
            model_name='crmopportunity',
            index=models.Index(fields=['stage', 'broker'], name='core_crmopp_stage_f00a8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmpropertylink',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('contact', 'property', 'relationship'), name='unique_crm_contact_property_relationship'),
        ),
        migrations.AddConstraint(
            model_name='crmpropertylink',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', True), models.Q(('unit_reference', ''), _negated=True)), fields=('contact', 'development_name', 'unit_reference', 'relationship'), name='unique_crm_contact_external_unit'),
        ),
        migrations.AddConstraint(
            model_name='crmproposal',
            constraint=models.UniqueConstraint(fields=('opportunity', 'version'), name='unique_crm_proposal_version'),
        ),
    ]
