# Generated by Django 5.2.1 on 2026-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_crmcontact_crmimportbatch_crmimportrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmimportbatch',
            name='source_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
