# Generated by Django 5.2.1 on 2026-08-03 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_crmimportbatch_source_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='role',
            field=models.CharField(choices=[('manager', 'Gestor comercial'), ('broker', 'Corretor')], db_index=True, default='broker', max_length=20),
        ),
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CRMNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('assignment', 'Nova atribuição'), ('task_due', 'Tarefa próxima'), ('task_overdue', 'Tarefa atrasada'), ('opportunity', 'Oportunidade'), ('system', 'Sistema')], db_index=True, default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], db_index=True, default='normal', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=240)),
                ('unique_key', models.CharField(blank=True, max_length=240, null=True, unique=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.broker')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notifications', to=settings.AUTH_USER_MODEL)),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.crmtask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='core_crmnot_recipie_4bb84a_idx')],
            },
        ),
    ]
