# Generated by Django 5.2.1 on 2026-08-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_broker_property_access_contact_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmopportunity',
            name='stage',
            field=models.CharField(choices=[('new', 'Lead recebido'), ('contacted', 'Contato realizado'), ('visit', 'Visita agendada'), ('proposal', 'Proposta enviada'), ('negotiation', 'Negociação'), ('won', 'Fechado'), ('lost', 'Perdido'), ('paused', 'Pausado'), ('released', 'Devolvido à fila')], db_index=True, default='new', max_length=20),
        ),
    ]
